version: '3'

services:
  app:
    build:
      context: .
    container_name: Task-Management-System
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8080:8080'

  db:
    image: postgres:15.5-alpine
    container_name: postgres-task-management-system
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d