version: '3'

services:
  app:
    build:
      context: .
    container_name: Task-Management-System
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task-management-system?currentSchema=task-management-system
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - '8080:8080'

  db:
    image: postgres:15.5-alpine
    container_name: postgres-task-management-system
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task-management-system
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d