spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
#  liquibase:
#    change-log: classpath:db/liquibase/db.changelog.yaml
#    enabled: true
#    default-schema: task-management-system
#    liquibase-schema: ${POSTGRES_SCHEMA}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: validate
    generate-ddl: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.springframework.web: ERROR
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    site.ph0en1x.taskmanagementsystem: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1 #hours
    refresh: 30 #days

springdoc:
  override-with-generic-response: false